language: python
python:
    - "3.4"
    - "3.6"
dist: trusty
sudo: required

cache:
  directories:
  - bincache

git:
  submodules: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - zlib1g-dev
      - libncurses5-dev
      - python3-all-dev
      - libhdf5-dev
      - libatlas-base-dev
      - libopenblas-base
      - libopenblas-dev
      - libbz2-dev
      - liblzma-dev
      - libffi-dev


install:
  - echo $TRAVIS_PYTHON_VERSION
  - export CXX="g++-4.9" CC="gcc-4.9"
  - make install


script:
  - echo "No testing implemented"


before_deploy:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.4" ]]; then make docs; fi


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GHPAGES_TOKEN
  local_dir: docs/_build/html
  target_branch: gh-pages
  on:
    branch: master
    python: "3.4"
